
titlescreen

 COLUPF=212

 playfield:
    XX..X..X...X..XX................
    X..X.X.X..X.X.X.X.....XXX.......
    XX.X.X.XX.X.X.X.X....XXXXX......
    ......................XXXXX.....
    ...X...XX.....XXX......XXXX.X.X.
    ..X.X.X..X...XXXXXX.....XXX..X..
    ...XX.X..X..X...XXXX...XXXXXX...
    ....X.X..X..X....XXXXXXXXXX.....
    ..XX...XX....X....XXXXXXXX......
    .................X..XXXXX.......
    ................................
end
 
 drawscreen

 goto titlescreen